---
title: "My CV"
---

::: {style="display: flex; gap: 30px;"}

::: {style="width: 50%;"}
<div>

### Current position

**Ph.D. Student in Political Science** (2022-Present) <br> Universitat Pompeu Fabra, Barcelona, Spain. <br> Thesis Project Title: *"Crisis, Competition, and Campaigning: Citizens and Parties in 21st Century Politics"*. <br> Supervisor: Dr. Toni Rodon.

### Research

#### Publications

Rodríguez, I., Rodon, T., Unan, A., Herbig, L., Klüver, H., & Kuhn, T. (2025). Benchmarking pandemic response: How the UK's Vaccine Rollout Impacted Popular support for the EU, *British Journal of Political Science, 55*(e35), pp. 1-16. DOI: https://doi.org/10.1017/S0007123424000802

Herbig, L., Unan, A., Kuhn, T., Rodríguez, I., Rodon, T., & Klüver, H. (2025). Closed borders, closed minds? COVID-related border closures, EU support, and hostility towards immigrants, *European Journal of Political Research, 64*(4), pp.1923-1944. DOI: https://doi.org/10.1111/1475-6765.70025

Rodon, T. & Rodríguez, I. (2024). A bitter victory and a sweet defeat: the July 2023 Spanish general election, *South European Society and Politics, 28*(3), pp. 335-357. DOI: https://doi.org/10.1080/13608746.2024.2326300


#### Revise & Resubmit

Rodríguez, I. *Legitimising prejudice? The impact of radical right party presence on anti-immigration attitude expression*. Electoral Studies.

#### In progress

Rodríguez, I., Rodon, T., & Dickson, Z. *A coordinated solution for a coordination problem? A Civic Education experiment on climate change and attitudes towards the European Union*.

Rodríguez, I. *Digital battlegrounds: How political parties tailor advertising to electoral contexts*.

Rodríguez, I. *One seat ahead: The impact of narrow electoral wins on political parties' digital ad strategy*.

### Participation in projects

**COVIDEU Project** <br> 
- VolkswagenStiftung Research Project <br> 
- Role: PhD Researcher <br> 
- Duration: 2022-2025 <br> 
- Principal Investigators: Dr. Heike Klüver (HU Berlin), Dr. Toni Rodon (UPF), Dr. Theresa Kuhn (LSE), Dr. Michal Krawczyk <br> 
- Website: [www.covideu.info](https://www.covideu.info)

**Unraveling reference points in the evaluation of regional governance indicators** <br>
- Institut d'Estudis d'Autogovern <br>
- Role: PhD Researcher <br>
- Duration: 2026-2027 <br>
- Principal Investigator: Dr. Jordi Mas (UOC) <br>


### Workshops

**I, II, III & IV COVIDEU Workshop**: *Project Workshop* <br> - 2022, 2023, 2024, 2025 <br> - University of Amsterdam, UPF, London School of Economics, HU Berlin

**Using AI for Text Analysis**: *Online course* <br> Febrary 2025 <br> - InStats <br> - Instructor: Seraphine Maerz <br> - <a href="AI Course_Certificate.pdf#" class="download" title="Course certificate">Course certificate</a>

**RECSM Summer Methods School**: *Big Data: Computational Analysis of Text* <br> - July 2022 <br> -  Universitat Pompeu Fabra <br> - Instructor: Carlos Arcila (Universidad de Salamanca) <br> - <a href="BigData_Certificate.pdf#" class="download" title="Course certificate">Course certificate</a>

**RECSM Summer Methods School**: *Multilevel I: Introduction to Multilevel Models* <br> - July 2022 <br> - Universitat Pompeu Fabray <br> - Instructors: Carla Rampichini and Leonardo Grilli (Università di Firenze) <br> - <a href="MultilevelI_Certificate.pdf#" class="download" title="Course certificate">Course certificate</a>

**VI & X PhD Workshop on Empirical Political Science** <br> - June 2022, June 2024 <br> - Universitat Pompeu Fabra, Universitat de Barcelona <br>

**PhD Programme in Political and Social Sciences**: *Doctoral Workshop* <br> - March 2022, March 2023, March 2024 <br> - Universitat Pompeu Fabra

**UPF PhD Program**: *Working with Concepts in the Social Sciences* <br> - February 2022 <br> - Universitat Pompeu Fabra <br> - Instructor: Frederic Schaffer (University of Massachussets) <br> - <a href="Concepts_Certificate.pdf#" class="download" title="Course certificate">Course certificate</a>

### Education

**Postgraduate Degree in Data Analysis** (2021-2022) <br> Universitat de Barcelona (Spain).

**MSc in Political Analysis and Institutional Assessment** (2020-2021) <br> Universitat de Barcelona (Spain). <br> Thesis Title: *"The entry of Vox in the Spanish political institutions and its effect on citizens' attitudes towards immigration"*.

**BA in Political Science and Administration** (2016-2020) <br> Universitat de Girona (Spain).

</div>
:::

::: {style="width: 50%;"}
<div>

### Research stays

**Research Stay at Humboldt-Universität zu Berlin** <br>
- Dynamics Research Training Group (RTG) <br>
- Under the supervision of Dr. Heike Klüver <br>
- October–December 2025 <br>

### Invited Talks and Presentations 

**Dynamics Research Training Group Seminar, Humboldt-Universität zu Berlin** <br>
- November 2025 <br>
- Presented: *One seat ahead: The impact of narrow electoral wins on political parties' digital ad strategy*. <br>

**Barcelona Program for Interdisciplinary Studies, Universitat Pompeu Fabra** <br>
- January 2025 <br>
- *Society and Politics in Contemporary Spain: the digital advertising strategies of political parties*.

**Universitat de l'Experiència, Universitat de Barcelona** <br>
- November 2021 <br>
- Seminar on *voter behavior and radical right parties*.


### Teaching

**Universitat Pompeu Fabra** (2022-2026) <br>

Teaching Assistant <br>

- *Quantitative Methodology IV* (BA in Political Science and Administration). <br>
- *Political Behavior and Public Opinion* (BA in Political Science and Administration).
- *Actors and Political Institutions* (BA in Political Science and Administration). <br>
- *Qualitative Methodology II* (BA in Political Science and Administration).

Instructor <br>

- *Crash Course on Basic Statistics and R* (BA in Journalism). <br>


**Universitat Oberta de Catalunya** (2025-2026) <br>

Adjunct lecturer ("professor col·laborador") <br>

- *Politics and Society* (BA in Political Science and Administration). <br>
- *Data visualisation and analysis* (BA in Political Science and Administration). <br>
- *Electoral analysis and public opinion* (BA in Political Science and Administration). <br>


### Conferences

**European Political Science Association, June 2025.** <br> Presenting: Rodríguez, I. *Digital battlegrounds: How political parties tailor advertising to electoral contexts*. [Working paper]

**European Political Science Association, July 2024.** <br> Presenting: Rodríguez, I., & Rodon, T. *A coordinated solution for a coordinated problem? A Civic Education experiment on climate change and attitudes towards the European Union* as part of the [COVIDEU Project](https://www.covideu.info). [Working paper]

**European Political Science Association, June 2023.** <br> Presenting: Rodríguez, I., Unan, A., Rodon, T., Klüver, H., & Kuhn, T.  *Benchmarking pandemic response: How the UK's Vaccine Rollout Impacted Popular support for the EU* as part of the [COVIDEU Project](https://www.covideu.info) and Rodríguez, I. *The dangers of legitimation: how the presence of an RRP in parliament can increase antiimmigration attitudes*. [Working paper]

**Midwest Political Science Association, April 2023.** <br> Presenting: Rodríguez, I., Unan, A., Rodon, T., Klüver, H., & Kuhn, T. *Benchmarking pandemic response: How the UK's Vaccine Rollout Impacted Popular support for the EU* as part of the [COVIDEU Project](https://www.covideu.info).

### Awards and Honors

**Beca Santander | Ayuda Económica Para Personal Investigador Predoctoral 2025 (Santander Grant | Financial Aid for Pre-Doctoral Researchers 2025)** <br>
- Banco Santander <br>
- €2,000 <br>

**PhD Programme in Political and Social Sciences Doctoral Workshop - Best Poster Award** <br> - Universitat Pompeu Fabra <br> - 2nd place <br> - Check out my <a href="IreneRodriguez_Poster_PhDWorkshop.pdf#" class="download" title="poster">poster</a>


### Skills/Languages

**Programming**: R (Expert in Data Analysis for Political Analysis and Public Administration) <br> **Markup**: Markdown/RMarkdown, LaTeX, Quarto <br> **Natural**: Spanish (native), Catalan (native), English (proficient), German (intermediate)


### Download my CV

Here you can find an updated PDF version of my CV: <a href="Irene_Rodriguez_CV copia.pdf#" class="download" title="Download CV as PDF">Download CV</a>


</div>
:::
:::
